name: Deploy_Kube_Prometheus_Stack

parameters:
  - name: deploy_kube_prometheus_stack
    displayName: Deploy Kube Prometheus Stack?
    type: boolean
    default: false

variables:
  - name: vault_address
    value: http://vault.cubicnextcloud.com.au:8200
  - name: vault_mount
    value: projects
  - name: vault_secrets_path
    value: nts_new_zealand/sbx
  - name: pool_name
    value: APAC_CubicNextCloud
  - name: roleId
    value: role_id.txt
  - name: secretId
    value: secret_id.txt

trigger: none
pr: none

stages:
  - stage: Deploy_Prometheus
    displayName: Deploy Prometheus Stack to AKS
    condition: eq('${{ parameters.deploy_kube_prometheus_stack }}', true)
    jobs:
      - job: Helm_Deploy
        displayName: Helm Install kube-prometheus-stack
        pool: ${{ variables.pool_name }}
        workspace:
          clean: all
        steps:

          - task: DownloadSecureFile@1
            name: DownloadRoleId
            inputs:
              secureFile: 'role_id.txt'

          - task: DownloadSecureFile@1
            name: DownloadSecretId
            inputs:
              secureFile: 'secret_id.txt'

          - task: HelmInstaller@1
            inputs:
              helmVersionToInstall: 'latest'

          - script: |
              echo "Installing kubelogin"
              curl -L -o kubelogin.zip https://github.com/Azure/kubelogin/releases/latest/download/kubelogin-linux-amd64.zip
              unzip kubelogin.zip -d kubelogin
              chmod +x kubelogin/bin/linux_amd64/kubelogin
              export PATH=$PATH:$(pwd)/kubelogin/bin/linux_amd64

              echo "Setting environment variables"
              export ROLE_ID=$(cat $(DownloadRoleId.secureFilePath))
              export SECRET_ID=$(cat $(DownloadSecretId.secureFilePath))
              export VAULT_ADDR=${{ variables.vault_address }}
              export VAULT_MOUNT=${{ variables.vault_mount }}
              export SECRETS_PATH=${{ variables.vault_secrets_path }}

              echo "Logging into Vault"
              VAULT_TOKEN=$(vault write -format=json auth/approle/login role_id=$ROLE_ID secret_id=$SECRET_ID | jq -r .auth.client_token)

              echo "Fetching Azure credentials from Vault"
              CLIENT_ID=$(vault kv get -field=azure_application_id $VAULT_MOUNT/$SECRETS_PATH/azure)
              CLIENT_SECRET=$(vault kv get -field=azure_application_secret $VAULT_MOUNT/$SECRETS_PATH/azure)
              TENANT_ID=$(vault kv get -field=tenant_id $VAULT_MOUNT/$SECRETS_PATH/azure)
              SUBSCRIPTION_ID=$(vault kv get -field=subscription_id $VAULT_MOUNT/$SECRETS_PATH/azure)
              RESOURCE_GROUP=$(vault kv get -field=azure_resource_group_name $VAULT_MOUNT/$SECRETS_PATH/azure)
              CLUSTER_NAME=$(vault kv get -field=cluster_name_pci $VAULT_MOUNT/$SECRETS_PATH/azure)

              echo "Logging into Azure"
              az login --output none --service-principal -u $CLIENT_ID -p $CLIENT_SECRET --tenant $TENANT_ID
              az account set --subscription $SUBSCRIPTION_ID

              echo "Getting AKS credentials"
              az aks get-credentials --overwrite-existing --resource-group $RESOURCE_GROUP --name $CLUSTER_NAME

              echo "Converting kubeconfig with kubelogin"
              kubelogin convert-kubeconfig -l spn --client-id $CLIENT_ID --client-secret $CLIENT_SECRET

              echo "Fetching Helm values from Vault"
              vault kv get -format=json $VAULT_MOUNT/$SECRETS_PATH/prometheus | jq -r '.data.data' > prometheus-values.yaml

              echo "Adding Helm repositories"
              helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
              helm repo add grafana https://grafana.github.io/helm-charts
              helm repo update

              echo "Deploying kube-prometheus-stack version 77.0.2"
              helm upgrade --install prometheus prometheus-community/kube-prometheus-stack \
                --namespace monitoring --create-namespace \
                --version 77.0.2 \
                --values prometheus-values.yaml \
                --atomic --debug
            displayName: 'Install kubelogin and Deploy Prometheus Stack'
